quarkus:
    http:
      cors: true
    mongodb:
      database: screenCastDB
    jaeger:
      service-name: scapersistservice
      sampler-type: const
      sampler-param: 1



"%local":
  quarkus:
    profile: local
    mongodb:
      connection-string: mongodb://localhost:27017



"%openshift":
  quarkus:
    profile: openshift
    mongodb:
      connection-string: mongodb://localhost:27017
    jaeger:
      endpoint: http://jaeger-collector:14268/api/traces